export const ADMIN_TABS = [
  {
    key: 'overview',
    label: 'Overview',
    description: 'Vue synthétique des KPI, alertes, objectifs, quick actions et activité admin récente.',
    sectionKeys: ['analytics', 'transactions', 'users', 'reviews', 'notifications', 'objectives', 'trustIndicators', 'admins', 'adminLogs', 'branding', 'payments', 'content', 'security'],
    sensitive: false,
    viewPermission: 'overviewView',
    editPermission: 'overviewView',
  },
  {
    key: 'branding',
    label: 'Branding & identité',
    description: 'Nom, logo, palette, footer, réseaux, trust bar et annonce globale.',
    sectionKeys: ['branding', 'footer', 'socialLinks', 'theme', 'trustIndicators', 'ui'],
    sensitive: false,
    viewPermission: 'brandingView',
    editPermission: 'brandingEdit',
  },
  {
    key: 'payments',
    label: 'Paiements & comptes',
    description: 'PayPal, Paysafecard, wallets crypto et délais de confirmation.',
    sectionKeys: ['payments'],
    sensitive: true,
    viewPermission: 'paymentsView',
    editPermission: 'paymentsEdit',
  },
  {
    key: 'exchangeRules',
    label: 'Frais & règles d’échange',
    description: 'Frais, limites, taux fixes, messages de validation et combinaisons actives.',
    sectionKeys: ['exchange'],
    sensitive: true,
    viewPermission: 'exchangeRulesView',
    editPermission: 'exchangeRulesEdit',
  },
  {
    key: 'users',
    label: 'Gestion des utilisateurs',
    description: 'Base locale d’utilisateurs, recherche, statuts, KYC, tags et soldes.',
    sectionKeys: ['users'],
    sensitive: false,
    viewPermission: 'usersView',
    editPermission: 'usersEdit',
  },
  {
    key: 'transactions',
    label: 'Gestion des transactions',
    description: 'Table d’opérations, filtres, compteurs, export CSV et édition rapide.',
    sectionKeys: ['transactions', 'analytics'],
    sensitive: false,
    viewPermission: 'transactionsView',
    editPermission: 'transactionsEdit',
  },
  {
    key: 'reviews',
    label: 'Avis & preuve sociale',
    description: 'Gestion des cartes d’avis, catégories, featured, langues et notation moyenne.',
    sectionKeys: ['reviews', 'trustIndicators'],
    sensitive: false,
    viewPermission: 'reviewsView',
    editPermission: 'reviewsEdit',
  },
  {
    key: 'notifications',
    label: 'Notifications & annonces',
    description: 'Toasts, bandeaux, messages dashboard, ciblage par page et historique.',
    sectionKeys: ['notifications', 'branding'],
    sensitive: true,
    viewPermission: 'notificationsView',
    editPermission: 'notificationsEdit',
  },
  {
    key: 'content',
    label: 'Content FR / EN',
    description: 'Tous les textes visibles du site : hero, login, exchange, FAQ, dashboard, maintenance.',
    sectionKeys: ['content'],
    sensitive: false,
    viewPermission: 'contentView',
    editPermission: 'contentEdit',
  },
  {
    key: 'market',
    label: 'Marché & cryptos',
    description: 'Actifs visibles, ordre d’affichage, prix locaux, variations et featured assets.',
    sectionKeys: ['market'],
    sensitive: false,
    viewPermission: 'marketView',
    editPermission: 'marketEdit',
  },
  {
    key: 'analytics',
    label: 'Analytics & stats',
    description: 'KPI, volumes, top assets, top flows et synthèse satisfaction.',
    sectionKeys: ['analytics'],
    sensitive: true,
    viewPermission: 'analyticsView',
    editPermission: 'analyticsEdit',
  },
  {
    key: 'objectives',
    label: 'Objectives',
    description: 'Objectifs mensuels, progression, tendance et statut à risque / atteint.',
    sectionKeys: ['objectives', 'analytics', 'trustIndicators'],
    sensitive: false,
    viewPermission: 'objectivesView',
    editPermission: 'objectivesEdit',
  },
  {
    key: 'adminsRoles',
    label: 'Admins & roles',
    description: 'Comptes admin, rôles, permissions fines, statuts et dernières connexions.',
    sectionKeys: ['admins', 'adminRoles'],
    sensitive: true,
    viewPermission: 'adminsView',
    editPermission: 'adminsEdit',
  },
  {
    key: 'passwordResets',
    label: 'Password resets',
    description: 'Demandes de réinitialisation, traitement support et mots de passe temporaires.',
    sectionKeys: ['passwordResets', 'users', 'admins'],
    sensitive: true,
    viewPermission: 'passwordResetsView',
    editPermission: 'passwordResetsEdit',
  },
  {
    key: 'security',
    label: 'Sécurité & accès',
    description: 'PIN secondaire, maintenance, accès admin, sessions locales et historique.',
    sectionKeys: ['security', 'adminAccess', 'adminLogs'],
    sensitive: true,
    viewPermission: 'securityView',
    editPermission: 'securityEdit',
  },
  {
    key: 'helpCenter',
    label: 'Help Center',
    description: 'Aide admin, checklist de préparation et diagnostic rapide de configuration.',
    sectionKeys: ['branding', 'payments', 'content', 'market', 'admins', 'reviews', 'security', 'notifications'],
    sensitive: false,
    viewPermission: 'helpView',
    editPermission: 'helpView',
  },
  {
    key: 'logs',
    label: 'Logs',
    description: 'Historique détaillé des connexions, sauvegardes, éditions et actions sensibles.',
    sectionKeys: ['adminLogs'],
    sensitive: false,
    viewPermission: 'logsView',
    editPermission: 'logsView',
  },
];
