export const defaultConfig = {
  meta: {
    schemaVersion: 2,
  },
  branding: {
    siteName: 'NovaBridge',
    shortName: 'NB',
    tagline: 'Plateforme d’échange crypto ↔ PayPal, version démo premium',
    logoUrl: '',
    logoDataUrl: '',
    faviconUrl: '/logo-mark.svg',
    supportEmail: 'support@novabridge.dev',
    domain: 'novabridge.dev',
    primaryColor: '#5ea4ff',
    secondaryColor: '#7ee0ff',
    themeMode: 'dark',
    footerCopyright: '© 2026 NovaBridge. Tous droits réservés.',
    footerLinks: [
      { label: 'Mentions légales', url: '#' },
      { label: 'Politique de confidentialité', url: '#' },
      { label: 'CGU', url: '#' },
    ],
    socials: {
      twitter: 'https://twitter.com/novabridge',
      telegram: 'https://t.me/novabridge',
      discord: 'https://discord.gg/novabridge',
    },
  },
  payments: {
    paypalEmail: 'pay@novabridge.dev',
    paypalDisplayName: 'NovaBridge Payout',
    postPaymentMessage: 'Votre paiement est en cours de vérification. Notre équipe confirme la réception dès que le dépôt réseau est validé.',
    confirmationDelay: '2-24h',
    methods: {
      BTC: {
        enabled: true,
        address: 'bc1qnovabridgebtc0000000000000000000',
        networkLabel: 'Bitcoin',
      },
      ETH: {
        enabled: true,
        address: '0xNovaBridgeEth0000000000000000000000',
        networkLabel: 'Ethereum',
      },
      USDT: {
        enabled: true,
        address: 'TKNovaBridgeUsdt000000000000000000000',
        networkLabel: 'USDT',
        network: 'TRC20',
      },
      LTC: {
        enabled: true,
        address: 'ltc1qnovabridgeltc0000000000000000000',
        networkLabel: 'Litecoin',
      },
      BNB: {
        enabled: false,
        address: '',
        networkLabel: 'BNB Smart Chain',
      },
      XRP: {
        enabled: false,
        address: '',
        networkLabel: 'XRP Ledger',
      },
    },
  },
  exchange: {
    globalFeePercent: 2.8,
    minAmount: 50,
    maxAmount: 5000,
    manualRateMode: false,
    warningMessage:
      'Les conversions sont simulées côté front. Remplace ensuite ce calcul local par ton endpoint de quote pour une version branchée backend.',
    assetFees: {
      BTC: 2.8,
      ETH: 2.4,
      USDT: 1.2,
      LTC: 2.1,
      BNB: 2.0,
      XRP: 1.8,
    },
    fixedRates: {
      BTC: 67244,
      ETH: 3486,
      USDT: 1,
      LTC: 87,
      BNB: 412,
      XRP: 0.54,
    },
    enabledPairs: {
      BTC: true,
      ETH: true,
      USDT: true,
      LTC: true,
      BNB: false,
      XRP: false,
    },
  },
  users: [
    {
      id: 'USR-001',
      name: 'Lina Martin',
      email: 'lina@novabridge.dev',
      createdAt: '2026-03-20T14:20:00.000Z',
      balance: 381.44,
      status: 'Actif',
      kyc: 'Vérifié',
    },
    {
      id: 'USR-002',
      name: 'Hugo Bernard',
      email: 'hugo@novabridge.dev',
      createdAt: '2026-03-22T09:12:00.000Z',
      balance: 941.76,
      status: 'Vérifié',
      kyc: 'En cours',
    },
    {
      id: 'USR-003',
      name: 'Mina Diallo',
      email: 'mina@novabridge.dev',
      createdAt: '2026-03-24T21:05:00.000Z',
      balance: 681.21,
      status: 'Suspendu',
      kyc: 'Non vérifié',
    },
  ],
  transactions: [
    {
      id: 'TX-1042',
      userId: 'USR-001',
      userName: 'Lina Martin',
      userEmail: 'lina@novabridge.dev',
      type: 'Crypto → PayPal',
      amount: 381.44,
      crypto: 'BTC',
      quantity: 0.0062,
      payoutMethod: 'PayPal',
      status: 'Confirmée',
      date: '2026-03-25T14:20:00.000Z',
    },
    {
      id: 'TX-1041',
      userId: 'USR-002',
      userName: 'Hugo Bernard',
      userEmail: 'hugo@novabridge.dev',
      type: 'Crypto → PayPal',
      amount: 941.76,
      crypto: 'ETH',
      quantity: 0.28,
      payoutMethod: 'PayPal',
      status: 'En attente',
      date: '2026-03-25T09:12:00.000Z',
    },
    {
      id: 'TX-1040',
      userId: 'USR-003',
      userName: 'Mina Diallo',
      userEmail: 'mina@novabridge.dev',
      type: 'Crypto → PayPal',
      amount: 681.21,
      crypto: 'USDT',
      quantity: 700,
      payoutMethod: 'PayPal',
      status: 'Confirmée',
      date: '2026-03-24T21:05:00.000Z',
    },
    {
      id: 'TX-1039',
      userId: 'USR-001',
      userName: 'Lina Martin',
      userEmail: 'lina@novabridge.dev',
      type: 'Crypto → PayPal',
      amount: 687.3,
      crypto: 'LTC',
      quantity: 8.5,
      payoutMethod: 'PayPal',
      status: 'En cours',
      date: '2026-03-24T16:33:00.000Z',
    },
  ],
  content: {
    announcement: {
      enabled: true,
      tone: 'info',
      text: 'Traitement prioritaire activé sur BTC, ETH et USDT aujourd’hui.',
    },
    home: {
      heroTitle: 'Une interface crypto premium, prête à piloter depuis un panel admin complet.',
      heroSubtitle:
        'Landing sombre, exchange, dashboard, transactions et panneau d’administration avancé. Tout fonctionne côté front sans backend obligatoire.',
      primaryCtaText: 'Ouvrir l’exchange',
      secondaryCtaText: 'Ouvrir l’admin',
      reasons: [
        {
          title: 'Pilotage complet',
          description: 'Gère le branding, les paiements, les règles d’échange et les contenus depuis une interface unique.',
        },
        {
          title: 'Mock data réaliste',
          description: 'Utilisateurs, transactions, analytics et marché sont éditables en localStorage pour tes démos.',
        },
        {
          title: 'Déploiement Vercel simple',
          description: 'Aucune dépendance serveur imposée, aucun Prisma, aucun build exotique à maintenir.',
        },
      ],
      steps: [
        'Choisis une crypto active dans le formulaire Exchange.',
        'Consulte instantanément l’estimation nette après frais.',
        'Confirme la transaction et suis son historique dans le dashboard.',
      ],
    },
    exchange: {
      intro:
        'Cette page de démonstration utilise un moteur de quote côté front. Elle est pensée pour être branchée plus tard à ton backend réel si tu le souhaites.',
      warning:
        'Les montants affichés restent simulés tant que le mode API live n’est pas branché.',
      confirmationMessage:
        'Merci. Votre demande a été créée et transmise à l’équipe de traitement.',
    },
    dashboard: {
      welcomeMessage: 'Bienvenue dans votre espace opérateur. Surveillez les conversions, les délais et le volume en un coup d’œil.',
    },
    footer: {
      text: 'NovaBridge est une démo front fintech/crypto conçue pour tester rapidement des parcours d’échange et des interfaces de pilotage.',
    },
    login: {
      title: 'Connexion locale',
      subtitle: 'Pas de backend ici : la session admin est simulée côté navigateur pour que tu puisses tester le panel complet.',
      errorMessage: 'Identifiants invalides. Utilise le compte admin configuré dans l’onglet Sécurité.',
    },
  },
  market: {
    livePricingEnabled: false,
    assets: [
      {
        id: 'BTC',
        symbol: 'BTC',
        name: 'Bitcoin',
        iconUrl: '',
        price: 67244,
        change24h: 3.2,
        volume: 18400000000,
        marketCap: 1320000000000,
        series: [58, 61, 60, 63, 67, 69, 72],
        enabledInMarket: true,
        enabledInExchange: true,
        position: 1,
      },
      {
        id: 'ETH',
        symbol: 'ETH',
        name: 'Ethereum',
        iconUrl: '',
        price: 3486,
        change24h: 2.14,
        volume: 9100000000,
        marketCap: 420000000000,
        series: [44, 46, 45, 47, 49, 50, 53],
        enabledInMarket: true,
        enabledInExchange: true,
        position: 2,
      },
      {
        id: 'USDT',
        symbol: 'USDT',
        name: 'Tether',
        iconUrl: '',
        price: 1,
        change24h: 0.02,
        volume: 31200000000,
        marketCap: 101000000000,
        series: [50, 50, 51, 50, 50, 49, 50],
        enabledInMarket: true,
        enabledInExchange: true,
        position: 3,
      },
      {
        id: 'LTC',
        symbol: 'LTC',
        name: 'Litecoin',
        iconUrl: '',
        price: 87,
        change24h: -1.37,
        volume: 620000000,
        marketCap: 6500000000,
        series: [65, 63, 62, 61, 60, 58, 57],
        enabledInMarket: true,
        enabledInExchange: true,
        position: 4,
      },
      {
        id: 'BNB',
        symbol: 'BNB',
        name: 'BNB',
        iconUrl: '',
        price: 412,
        change24h: 1.12,
        volume: 1100000000,
        marketCap: 62000000000,
        series: [38, 41, 42, 44, 45, 46, 47],
        enabledInMarket: false,
        enabledInExchange: false,
        position: 5,
      },
      {
        id: 'XRP',
        symbol: 'XRP',
        name: 'XRP',
        iconUrl: '',
        price: 0.54,
        change24h: -0.84,
        volume: 860000000,
        marketCap: 29000000000,
        series: [55, 54, 53, 54, 52, 51, 50],
        enabledInMarket: false,
        enabledInExchange: false,
        position: 6,
      },
    ],
  },
  security: {
    admin: {
      username: 'admin@novabridge.dev',
      passwordHash: '0ead2060b65992dca4769af601a1b3a35ef38cfad2c2c465bb160ea764157c5d',
      pinEnabled: false,
      pinHash: '',
      lastPasswordChange: '2026-03-24T12:00:00.000Z',
    },
    loginPageEnabled: true,
    maintenanceMode: false,
    maintenanceTitle: 'Maintenance en cours',
    maintenanceMessage: 'Le site est momentanément indisponible. Merci de revenir dans quelques instants.',
    adminLoginHistory: [
      {
        id: 'LOGIN-001',
        email: 'admin@novabridge.dev',
        at: '2026-03-25T09:12:00.000Z',
      },
      {
        id: 'LOGIN-002',
        email: 'admin@novabridge.dev',
        at: '2026-03-24T18:42:00.000Z',
      },
    ],
  },
  notifications: {
    dashboardEnabled: true,
    items: [
      {
        id: 'NTF-001',
        type: 'info',
        message: 'Les transactions BTC sont traitées en priorité aujourd’hui.',
        durationMs: 4500,
        target: 'all',
        enabled: true,
        createdAt: '2026-03-26T10:00:00.000Z',
      },
    ],
    history: [
      {
        id: 'NTF-001',
        type: 'info',
        message: 'Les transactions BTC sont traitées en priorité aujourd’hui.',
        durationMs: 4500,
        target: 'all',
        enabled: true,
        createdAt: '2026-03-26T10:00:00.000Z',
      },
    ],
  },
  analytics: {
    volumeTotal: 428000,
    totalTransactions: 312,
    activeUsers: 184,
    averageTransaction: 684,
    peakHour: '19:00 - 21:00',
    dailyVolume7: [42000, 51000, 47000, 58000, 64000, 69000, 77000],
    dailyVolume30: [
      18000, 21000, 19000, 24000, 26000, 27000, 23000, 25000, 29000, 31000,
      32000, 28000, 34000, 36000, 39000, 41000, 43000, 45000, 47000, 50000,
      52000, 55000, 53000, 57000, 59000, 61000, 64000, 66000, 69000, 72000,
    ],
    assetDistribution: [
      { symbol: 'BTC', volume: 44 },
      { symbol: 'ETH', volume: 27 },
      { symbol: 'USDT', volume: 19 },
      { symbol: 'LTC', volume: 10 },
    ],
  },
};
