const currentYear = 2026;

function sparkline(seed, drift = 1) {
  return Array.from({ length: 7 }, (_, index) => {
    const base = 46 + seed * 5;
    const wave = Math.sin(index + seed) * 4.8;
    return Math.round(base + wave + index * drift);
  });
}

export const PERMISSION_KEYS = [
  'overviewView',
  'brandingView', 'brandingEdit',
  'paymentsView', 'paymentsEdit',
  'exchangeRulesView', 'exchangeRulesEdit',
  'usersView', 'usersEdit', 'usersSuspend',
  'transactionsView', 'transactionsEdit', 'transactionsExport',
  'reviewsView', 'reviewsEdit',
  'notificationsView', 'notificationsEdit',
  'contentView', 'contentEdit',
  'marketView', 'marketEdit',
  'analyticsView', 'analyticsEdit',
  'objectivesView', 'objectivesEdit',
  'adminsView', 'adminsEdit',
  'securityView', 'securityEdit',
  'helpView',
  'logsView',
  'maintenanceToggle',
];

export function createPermissionMap(enabledKeys = []) {
  const enabled = new Set(enabledKeys);
  return PERMISSION_KEYS.reduce((accumulator, key) => {
    accumulator[key] = enabled.has(key);
    return accumulator;
  }, {});
}

const FULL_PERMISSIONS = createPermissionMap(PERMISSION_KEYS);

export const ROLE_PRESETS = {
  owner: {
    label: 'Owner',
    level: 100,
    tone: 'danger',
    description: 'Contrôle absolu de la plateforme, des rôles, de la sécurité et des paramètres globaux.',
    permissions: FULL_PERMISSIONS,
  },
  superAdmin: {
    label: 'Super Admin',
    level: 95,
    tone: 'warning',
    description: 'Supervision complète de la plateforme, sans transfert de propriété.',
    permissions: createPermissionMap(PERMISSION_KEYS.filter((key) => key !== 'maintenanceToggle').concat('maintenanceToggle')),
  },
  platformAdmin: {
    label: 'Platform Admin',
    level: 88,
    tone: 'info',
    description: 'Pilote branding, contenus, marché, notifications, analytics et opérations globales.',
    permissions: createPermissionMap([
      'overviewView',
      'brandingView', 'brandingEdit',
      'paymentsView',
      'exchangeRulesView', 'exchangeRulesEdit',
      'usersView', 'usersEdit',
      'transactionsView', 'transactionsEdit', 'transactionsExport',
      'reviewsView', 'reviewsEdit',
      'notificationsView', 'notificationsEdit',
      'contentView', 'contentEdit',
      'marketView', 'marketEdit',
      'analyticsView', 'analyticsEdit',
      'objectivesView', 'objectivesEdit',
      'helpView',
      'logsView',
    ]),
  },
  securityAdmin: {
    label: 'Security Admin',
    level: 82,
    tone: 'danger',
    description: 'Audite l’accès admin, les connexions, le PIN secondaire et les paramètres sensibles.',
    permissions: createPermissionMap([
      'overviewView',
      'securityView', 'securityEdit',
      'adminsView', 'adminsEdit',
      'logsView',
      'helpView',
      'notificationsView',
      'usersView',
      'transactionsView',
      'maintenanceToggle',
    ]),
  },
  financeAdmin: {
    label: 'Finance Admin',
    level: 78,
    tone: 'success',
    description: 'Gère paiements, wallets, frais, flux, transactions et suivi volume/revenus.',
    permissions: createPermissionMap([
      'overviewView',
      'paymentsView', 'paymentsEdit',
      'exchangeRulesView', 'exchangeRulesEdit',
      'transactionsView', 'transactionsEdit', 'transactionsExport',
      'analyticsView', 'analyticsEdit',
      'usersView',
      'objectivesView',
      'helpView',
      'logsView',
    ]),
  },
  operationsAdmin: {
    label: 'Operations Admin',
    level: 72,
    tone: 'info',
    description: 'Supervise les opérations quotidiennes, les annonces, la modération des demandes et les alertes.',
    permissions: createPermissionMap([
      'overviewView',
      'usersView', 'usersEdit', 'usersSuspend',
      'transactionsView', 'transactionsEdit', 'transactionsExport',
      'notificationsView', 'notificationsEdit',
      'analyticsView',
      'helpView',
      'logsView',
      'reviewsView',
    ]),
  },
  complianceAdmin: {
    label: 'Compliance Admin',
    level: 66,
    tone: 'warning',
    description: 'Pilote les statuts KYC, les suspensions et les transactions à revoir.',
    permissions: createPermissionMap([
      'overviewView',
      'usersView', 'usersEdit', 'usersSuspend',
      'transactionsView', 'transactionsEdit',
      'logsView',
      'helpView',
    ]),
  },
  supportManager: {
    label: 'Support Manager',
    level: 58,
    tone: 'info',
    description: 'Suit les utilisateurs, notifications, demandes récentes et messages de support.',
    permissions: createPermissionMap([
      'overviewView',
      'usersView', 'usersEdit',
      'transactionsView',
      'notificationsView', 'notificationsEdit',
      'reviewsView',
      'contentView',
      'helpView',
      'logsView',
    ]),
  },
  contentAdmin: {
    label: 'Content Admin',
    level: 54,
    tone: 'secondary',
    description: 'Administre les textes FR/EN, le branding éditorial, la FAQ et les témoignages.',
    permissions: createPermissionMap([
      'overviewView',
      'brandingView', 'brandingEdit',
      'contentView', 'contentEdit',
      'reviewsView', 'reviewsEdit',
      'notificationsView',
      'marketView',
      'helpView',
    ]),
  },
  marketingAdmin: {
    label: 'Marketing Admin',
    level: 50,
    tone: 'secondary',
    description: 'Travaille la landing, la preuve sociale, les annonces éditoriales et les métriques publiques.',
    permissions: createPermissionMap([
      'overviewView',
      'contentView', 'contentEdit',
      'reviewsView', 'reviewsEdit',
      'notificationsView', 'notificationsEdit',
      'analyticsView',
      'helpView',
    ]),
  },
  analyst: {
    label: 'Analyst',
    level: 36,
    tone: 'neutral',
    description: 'Vue en lecture seule enrichie sur les volumes, transactions, objectifs et logs.',
    permissions: createPermissionMap([
      'overviewView',
      'usersView',
      'transactionsView', 'transactionsExport',
      'reviewsView',
      'analyticsView',
      'objectivesView',
      'helpView',
      'logsView',
    ]),
  },
  moderator: {
    label: 'Moderator',
    level: 28,
    tone: 'neutral',
    description: 'Lecture et actions limitées sur users, transactions et notifications.',
    permissions: createPermissionMap([
      'overviewView',
      'usersView',
      'transactionsView',
      'notificationsView',
      'helpView',
    ]),
  },
  viewer: {
    label: 'Viewer',
    level: 12,
    tone: 'neutral',
    description: 'Lecture seule basique pour supervision légère.',
    permissions: createPermissionMap([
      'overviewView',
      'analyticsView',
      'helpView',
    ]),
  },
};

const reviewSamples = [
  {
    id: 'REV-1001',
    author: 'Nadia R.',
    role: 'Utilisatrice vérifiée',
    text: "Vraiment excellent, tout est fluide et rapide. J'ai pu acheter du Bitcoin en moins de 5 minutes après mon inscription.",
    rating: 5,
    language: 'fr',
    category: 'Rapidite',
    verified: true,
    featured: true,
    avatarTone: '#3B82F6',
  },
  {
    id: 'REV-1002',
    author: 'Thomas B.',
    role: 'Utilisateur mobile',
    text: "Plateforme super intuitive, même pour quelqu'un comme moi qui n'y connaissait rien grand-chose. L'application mobile est au top.",
    rating: 5,
    language: 'fr',
    category: 'Mobile',
    verified: true,
    featured: true,
    avatarTone: '#8B5CF6',
  },
  {
    id: 'REV-1003',
    author: 'Sophie M.',
    role: 'Compte récurrent',
    text: 'Frais de transaction très bas comparés aux autres plateformes que j\'ai testées. C\'est devenu mon service principal.',
    rating: 5,
    language: 'fr',
    category: 'Frais',
    verified: true,
    featured: false,
    avatarTone: '#22C55E',
  },
  {
    id: 'REV-1004',
    author: 'Yanis L.',
    role: 'Utilisateur vérifié',
    text: 'Sécurité irréprochable. Les alertes et la clarté du suivi me rassurent complètement.',
    rating: 5,
    language: 'fr',
    category: 'Securite',
    verified: true,
    featured: true,
    avatarTone: '#F59E0B',
  },
  {
    id: 'REV-1005',
    author: 'Camille D.',
    role: 'Support experience',
    text: 'Le support client a répondu à ma question en moins d\'une heure. C\'est rare et très appréciable.',
    rating: 5,
    language: 'fr',
    category: 'Support',
    verified: true,
    featured: false,
    avatarTone: '#EF4444',
  },
  {
    id: 'REV-1006',
    author: 'Alex P.',
    role: 'Utilisateur régulier',
    text: "Avoir la possibilité de lier PayPal pour acheter des cryptos, c'est un vrai game changer. Super pratique.",
    rating: 5,
    language: 'fr',
    category: 'Simplicite',
    verified: true,
    featured: true,
    avatarTone: '#14B8A6',
  },
  {
    id: 'REV-1007',
    author: 'Mélina T.',
    role: 'Compte actif',
    text: "Le meilleur pour débuter. On nous guide pas à pas, c'est vraiment bien fait.",
    rating: 5,
    language: 'fr',
    category: 'Simplicite',
    verified: true,
    featured: true,
    avatarTone: '#F97316',
  },
  {
    id: 'REV-1008',
    author: 'Jules K.',
    role: 'Utilisateur avancé',
    text: 'Plateforme solide avec de bonnes fonctionnalités avancées. Parfait pour les traders un peu plus expérimentés.',
    rating: 4,
    language: 'fr',
    category: 'Rapidite',
    verified: true,
    featured: false,
    avatarTone: '#06B6D4',
  },
  {
    id: 'REV-1009',
    author: 'Emma S.',
    role: 'Verified user',
    text: 'Simple, fast and transparent. The guided flow removes the friction without feeling simplistic.',
    rating: 5,
    language: 'en',
    category: 'Simplicity',
    verified: true,
    featured: true,
    avatarTone: '#5B7CFA',
  },
  {
    id: 'REV-1010',
    author: 'Liam C.',
    role: 'Frequent buyer',
    text: 'The best rates I found for ETH and USDT. Everything stayed clear from start to confirmation.',
    rating: 5,
    language: 'en',
    category: 'Pricing',
    verified: true,
    featured: false,
    avatarTone: '#22C55E',
  },
  {
    id: 'REV-1011',
    author: 'Olivia N.',
    role: 'Mobile first user',
    text: 'The mobile experience is polished and easy to follow. I can complete a request in minutes.',
    rating: 5,
    language: 'en',
    category: 'Mobile',
    verified: true,
    featured: true,
    avatarTone: '#E879F9',
  },
  {
    id: 'REV-1012',
    author: 'Lucas F.',
    role: 'Utilisateur fidèle',
    text: 'Aucun frais caché, tout est transparent dès le départ. C\'est exactement ce que je cherchais.',
    rating: 5,
    language: 'fr',
    category: 'Frais',
    verified: true,
    featured: false,
    avatarTone: '#84CC16',
  },
  {
    id: 'REV-1013',
    author: 'Mia H.',
    role: 'Verified support case',
    text: 'Support was fast, competent and transparent. That matters a lot on a payments product.',
    rating: 5,
    language: 'en',
    category: 'Support',
    verified: true,
    featured: true,
    avatarTone: '#FB7185',
  },
  {
    id: 'REV-1014',
    author: 'Bastien A.',
    role: 'Utilisateur vérifié',
    text: 'Fiable, rapide, et avec une bonne réputation. Que demander de plus ?',
    rating: 5,
    language: 'fr',
    category: 'Rapidite',
    verified: true,
    featured: true,
    avatarTone: '#A78BFA',
  },
];

const frContent = {
  common: {
    login: 'Connexion',
    logout: 'Déconnexion',
    language: 'Langue',
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    openExchange: 'Commencer un échange',
    openAdmin: 'Ouvrir le panel admin',
    viewTransactions: 'Voir les transactions',
    continueAsGuest: 'Continuer en tant qu’invité',
    completeProfile: 'Compléter votre profil',
    guestSession: 'Session invitée',
    liveRatesPlanned: 'Mode live prévu',
  },
  nav: {
    home: 'Accueil',
    exchange: 'Exchange',
    market: 'Marché',
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    admin: 'Admin',
    login: 'Connexion',
  },
  home: {
    heroTitle: 'Échangez, encaissez et pilotez vos flux depuis une interface claire et ultra-rapide.',
    heroSubtitle: 'Plateforme crypto/paiement premium, front-only, responsive et guidée. Tout se pilote depuis un panel admin local complet, sans casser la simplicité du build Vite/Vercel.',
    primaryCta: 'Commencer un échange',
    secondaryCta: 'Découvrir le panel admin',
    trustBadge: 'Traitement guidé • Configuration centralisée • Session locale persistée',
    reasons: [
      {
        title: 'Rapide à comprendre',
        text: 'Chaque écran réduit la charge mentale : un seul objectif par bloc, des indicateurs clairs et des CTA visibles.',
      },
      {
        title: 'Crédible dès le premier regard',
        text: 'Hiérarchie visuelle nette, chiffres cohérents, avis vérifiés et composants homogènes sur tout le produit.',
      },
      {
        title: '100% pilotable',
        text: 'Branding, paiements, flux, objectifs, rôles, contenus FR/EN, alertes et analytics se gèrent depuis un seul panel.',
      },
      {
        title: 'Optimisé mobile-first',
        text: 'Le parcours fonctionne réellement sur téléphone : boutons larges, étapes courtes, sidebar transformée en bloc utile.',
      },
    ],
    steps: [
      {
        title: 'Choisissez votre flux',
        text: 'PayPal vers crypto, crypto vers PayPal, Paysafecard vers crypto ou Paysafecard vers PayPal selon la configuration active.',
      },
      {
        title: 'Renseignez la destination',
        text: 'Wallet crypto ou email PayPal : la destination est validée avant les instructions et visible dans le récapitulatif.',
      },
      {
        title: 'Confirmez et suivez',
        text: 'Chaque demande crée un dossier local avec ID, statut, estimation nette et suivi dans le dashboard et les transactions.',
      },
    ],
    faq: [
      {
        question: 'Les frais sont-ils affichés avant confirmation ?',
        answer: 'Oui. Les frais, le montant net estimé, les limites et le délai apparaissent avant la création finale du dossier.',
      },
      {
        question: 'Puis-je utiliser la plateforme sans compte ?',
        answer: 'Oui. Une session invitée locale permet d’accéder à l’exchange, au marché et à un dashboard allégé sur le même appareil.',
      },
      {
        question: 'Le panel admin modifie-t-il le site en direct ?',
        answer: 'Oui. Chaque sauvegarde répercute immédiatement les changements sur le branding, les contenus, les paiements et les règles.',
      },
      {
        question: 'Le projet reste-t-il compatible Vercel ?',
        answer: 'Oui. Il reste une SPA Vite front-only avec build simple, sans backend imposé.',
      },
    ],
  },
  exchange: {
    title: 'Moteur d’échange guidé',
    intro: 'Le moteur applique vos règles locales, vos frais, vos limites et vos combinaisons actives. Les instructions sont contextuelles et le suivi reste clair sur mobile comme sur desktop.',
    warning: 'Les montants affichés sont des estimations locales calculées avec la configuration active et sont vérifiés lors du traitement.',
    confirmationMessage: 'Votre demande a été enregistrée avec succès.',
    verificationMessage: 'Le dossier est en cours de vérification et de rapprochement.',
    postPaymentMessage: 'Une fois votre paiement ou votre envoi effectué, confirmez l’action pour transmettre la demande au desk.',
    flowLabels: {
      paypalToCrypto: 'PayPal → Crypto',
      cryptoToPaypal: 'Crypto → PayPal',
      paysafecardToCrypto: 'Paysafecard → Crypto',
      paysafecardToPaypal: 'Paysafecard → PayPal',
    },
    sideMessages: [
      'Les frais et montants nets restent visibles à chaque étape.',
      'Les coordonnées de paiement affichées reprennent la configuration active du panel admin.',
      'Les transactions créées restent consultables dans le dashboard et l’historique.',
    ],
  },
  dashboard: {
    title: 'Vue de compte',
    welcomeMessage: 'Retrouvez vos activités récentes, vos indicateurs clés, l’état de votre compte et les conditions de traitement en un coup d’œil.',
    accountMessage: 'Les états, badges, notifications et raccourcis sont optimisés pour un usage rapide sur mobile comme sur desktop.',
    guestMessage: 'Vous utilisez une session invitée locale. Vos opérations restent disponibles sur cet appareil tant que la session n’est pas réinitialisée.',
  },
  market: {
    title: 'Marché local',
    subtitle: 'Les actifs visibles ici sont pilotés depuis le panel admin. Prix, variations et ordre d’affichage restent éditables sans API obligatoire.',
  },
  transactions: {
    title: 'Historique des opérations',
    subtitle: 'Retrouvez vos dossiers, filtres et statuts dans une vue claire, lisible et optimisée pour tous les écrans.',
  },
  login: {
    title: 'Accédez à la plateforme',
    subtitle: 'Connexion utilisateur locale, accès admin par rôle et session invitée en un clic.',
    adminTitle: 'Accès administrateur',
    adminSubtitle: 'Connectez-vous avec l’un des comptes admin configurés dans Admins & Roles.',
    errorMessage: 'Les identifiants administrateur ne correspondent à aucun compte actif.',
    disabledMessage: 'Les connexions utilisateur sont actuellement désactivées. L’accès admin peut rester disponible selon la configuration.',
    userErrorMessage: 'Aucun profil utilisateur local ne correspond à cette adresse email.',
    guestTitle: 'Session invitée rapide',
    guestSubtitle: 'Commencez un échange sans créer de compte complet. Vous pourrez compléter vos informations plus tard sur le même appareil.',
  },
  maintenance: {
    title: 'Mise à jour opérationnelle en cours',
    message: 'La plateforme publique est temporairement indisponible pendant une courte intervention. Les accès admin peuvent rester ouverts selon la configuration.',
  },
  admin: {
    title: 'Pilotage admin',
    overview: 'Overview',
    helpTitle: 'Help Center',
  },
};

const enContent = {
  common: {
    login: 'Sign in',
    logout: 'Log out',
    language: 'Language',
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    openExchange: 'Start an exchange',
    openAdmin: 'Open admin panel',
    viewTransactions: 'View transactions',
    continueAsGuest: 'Continue as guest',
    completeProfile: 'Complete your profile',
    guestSession: 'Guest session',
    liveRatesPlanned: 'Live mode planned',
  },
  nav: {
    home: 'Home',
    exchange: 'Exchange',
    market: 'Market',
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    admin: 'Admin',
    login: 'Login',
  },
  home: {
    heroTitle: 'Swap, settle and manage payment flows from a fast and credible premium interface.',
    heroSubtitle: 'A premium crypto/payments platform, front-only, responsive and guided. Everything stays manageable from a complete local admin panel without breaking Vite/Vercel stability.',
    primaryCta: 'Start an exchange',
    secondaryCta: 'Explore the admin panel',
    trustBadge: 'Guided execution • Centralized configuration • Persistent local session',
    reasons: [
      {
        title: 'Fast to understand',
        text: 'Every screen reduces cognitive load with a single goal, visible feedback and a clear action hierarchy.',
      },
      {
        title: 'Credible at first glance',
        text: 'Clean visual hierarchy, coherent public metrics, verified reviews and consistent components across the product.',
      },
      {
        title: 'Fully manageable',
        text: 'Branding, payments, rules, objectives, roles, FR/EN content, alerts and analytics are controlled from one panel.',
      },
      {
        title: 'True mobile-first UX',
        text: 'The flow actually works on phones: larger actions, shorter steps and useful collapsible side information.',
      },
    ],
    steps: [
      {
        title: 'Choose your flow',
        text: 'PayPal to crypto, crypto to PayPal, Paysafecard to crypto or Paysafecard to PayPal depending on active availability.',
      },
      {
        title: 'Set the destination',
        text: 'A crypto wallet or a PayPal email is validated before instructions and remains visible in the final summary.',
      },
      {
        title: 'Confirm and follow up',
        text: 'Each request creates a local record with an ID, a status, a net estimate and dashboard visibility.',
      },
    ],
    faq: [
      {
        question: 'Are fees visible before confirmation?',
        answer: 'Yes. Fees, estimated net amount, limits and timing are shown before the request is created.',
      },
      {
        question: 'Can I use the platform without a full account?',
        answer: 'Yes. A local guest session lets you access exchange, market and a lightweight dashboard on the same device.',
      },
      {
        question: 'Does the admin panel update the site immediately?',
        answer: 'Yes. Every save reflects right away on branding, content, payments and exchange rules.',
      },
      {
        question: 'Does it remain Vercel compatible?',
        answer: 'Yes. It stays a front-only Vite SPA with a simple build and no mandatory backend.',
      },
    ],
  },
  exchange: {
    title: 'Guided exchange engine',
    intro: 'The engine applies local fees, limits, active combinations and contextual instructions, while staying easy to follow on every device.',
    warning: 'Displayed amounts are local estimates based on the active configuration and remain subject to verification during processing.',
    confirmationMessage: 'Your request has been registered successfully.',
    verificationMessage: 'The request is being verified and matched.',
    postPaymentMessage: 'Once your payment or transfer is completed, confirm the action to hand the request to the desk.',
    flowLabels: {
      paypalToCrypto: 'PayPal → Crypto',
      cryptoToPaypal: 'Crypto → PayPal',
      paysafecardToCrypto: 'Paysafecard → Crypto',
      paysafecardToPaypal: 'Paysafecard → PayPal',
    },
    sideMessages: [
      'Fees and net estimates remain visible at every step.',
      'Displayed payment details always follow the active admin configuration.',
      'Created requests stay visible in the dashboard and transactions history.',
    ],
  },
  dashboard: {
    title: 'Account overview',
    welcomeMessage: 'Track your latest activity, key indicators, account status and active processing conditions at a glance.',
    accountMessage: 'States, badges, notifications and shortcuts are optimized for both quick mobile use and larger screens.',
    guestMessage: 'You are currently using a local guest session. Your activity stays available on this device until the session is cleared.',
  },
  market: {
    title: 'Local market view',
    subtitle: 'Visible assets are controlled from the admin panel. Prices, variations and ordering remain editable without a mandatory API.',
  },
  transactions: {
    title: 'Operations history',
    subtitle: 'Track your requests, filters and statuses in a clean, readable layout on every screen.',
  },
  login: {
    title: 'Access the platform',
    subtitle: 'Local user login, role-based admin access and one-click guest sessions.',
    adminTitle: 'Administrator access',
    adminSubtitle: 'Sign in with one of the admin accounts configured in Admins & Roles.',
    errorMessage: 'The provided admin credentials do not match any active account.',
    disabledMessage: 'Public user login is currently disabled. Admin access may remain available depending on configuration.',
    userErrorMessage: 'No local user profile matches this email address.',
    guestTitle: 'Fast guest session',
    guestSubtitle: 'Start an exchange without creating a full account. You can enrich your profile later on the same device.',
  },
  maintenance: {
    title: 'Operational maintenance in progress',
    message: 'The public platform is temporarily unavailable during a short intervention. Admin access may remain available depending on configuration.',
  },
  admin: {
    title: 'Admin control center',
    overview: 'Overview',
    helpTitle: 'Help Center',
  },
};

export const defaultConfig = {
  meta: {
    schemaVersion: 4,
    storageVersion: 2,
    locale: 'fr-FR',
    currency: 'EUR',
  },
  ui: {
    language: 'fr',
    loaderEnabled: true,
    loaderText: {
      fr: 'Préparation de l’environnement d’échange sécurisé',
      en: 'Preparing secure exchange environment',
    },
    showTrustStrip: true,
  },
  branding: {
    siteName: 'Clyra Exchange',
    shortName: 'CLX',
    tagline: 'Exchange crypto & paiements pilotés depuis un panel premium',
    logoUrl: '',
    logoDataUrl: '',
    faviconUrl: '',
    supportEmail: 'support@clyra.exchange',
    announcementEnabled: true,
    announcementTone: 'info',
    announcementText: 'Fenêtre de traitement prioritaire active sur PayPal, BTC, ETH et USDT.',
  },
  footer: {
    text: 'Clyra Exchange propose une expérience d’échange crypto/paiement premium, front-only, pilotable localement et pensée pour rester claire sur tous les écrans.',
    copyright: `© ${currentYear} Clyra Exchange. Tous droits réservés.`,
    legalLinks: [
      { label: 'Mentions légales', url: '#legal' },
      { label: 'Politique de confidentialité', url: '#privacy' },
      { label: 'Conditions d’utilisation', url: '#terms' },
    ],
  },
  socialLinks: {
    twitter: 'https://twitter.com/',
    telegram: 'https://t.me/',
    discord: 'https://discord.com/',
    linkedin: 'https://linkedin.com/',
  },
  theme: {
    mode: 'dark',
    primary: '#3B82F6',
    secondary: '#8B5CF6',
  },
  trustIndicators: {
    monthlyVolume: 2840000,
    totalTransactions: 18426,
    activeUsers: 3840,
    averageRating: 4.8,
    reviewCount: 12408,
    supportSatisfaction: 97,
    averageProcessingMinutes: 11,
    completionRate: 98.9,
  },
  guestSession: {
    enabled: true,
    allowContactLink: true,
    suggestedContactMethods: ['email', 'discord', 'telegram'],
  },
  payments: {
    paypal: {
      enabled: true,
      paymentEnabled: true,
      receiveEnabled: true,
      email: 'settlement@clyra.exchange',
      accountName: 'Clyra Settlement Desk',
      postPaymentMessage: 'Votre demande a été transmise au desk de règlement. Une vérification de conformité et de réception est réalisée avant confirmation finale.',
      confirmationDelay: '5 à 30 minutes',
      instruction: 'Envoyez le montant exact et ajoutez la note de référence pour accélérer le rapprochement.',
      defaultNote: 'CLX-ORDER',
      autoGenerateNote: true,
    },
    paysafecard: {
      enabled: true,
      paymentEnabled: true,
      receiveEnabled: false,
      instructions: 'Préparez vos codes Paysafecard et transmettez-les une fois le dossier créé. Chaque code est contrôlé avant toute validation.',
      codeFormat: '16 chiffres par code',
      confirmationMessage: 'Les codes reçus sont vérifiés avant émission du règlement.',
      confirmationDelay: '10 à 45 minutes',
    },
    cryptoWallets: {
      BTC: {
        enabled: true,
        paymentEnabled: true,
        receiveEnabled: true,
        address: 'bc1q4m2d9k6y5t8u4r2w0clxexchange7h8s4u',
        networkLabel: 'Bitcoin',
        label: 'Trésorerie BTC',
      },
      ETH: {
        enabled: true,
        paymentEnabled: true,
        receiveEnabled: true,
        address: '0xC1yra7eB7fB4b31f0c22eA9ceF08d33c6A021234',
        networkLabel: 'Ethereum',
        label: 'Trésorerie ETH',
      },
      USDT: {
        enabled: true,
        paymentEnabled: true,
        receiveEnabled: true,
        address: 'TFmH7cLyRa9DeskF2wq8R5x6b3Jm9uQp2a',
        networkLabel: 'Tether',
        network: 'TRC20',
        label: 'Trésorerie USDT',
      },
      LTC: {
        enabled: true,
        paymentEnabled: true,
        receiveEnabled: true,
        address: 'ltc1qk2a8v3clyra4n8desk8m4p9y2s4c7z6r',
        networkLabel: 'Litecoin',
        label: 'Trésorerie LTC',
      },
      SOL: {
        enabled: true,
        paymentEnabled: true,
        receiveEnabled: true,
        address: '7nhKxQfClyraDesk4whB5y2m9sR7p1jY8qkL2uH8T3Ae',
        networkLabel: 'Solana',
        label: 'Trésorerie SOL',
      },
      BNB: {
        enabled: true,
        paymentEnabled: true,
        receiveEnabled: true,
        address: 'bnb1r5p8q9x4clyradesk0z7m2w6n5f4s2d9h7l3c',
        networkLabel: 'BNB Smart Chain',
        label: 'Trésorerie BNB',
      },
      XRP: {
        enabled: true,
        paymentEnabled: true,
        receiveEnabled: true,
        address: 'rClyraDesk4zQ7f6h2p4k9m8s2w1n0x5u7v',
        networkLabel: 'XRP Ledger',
        destinationTag: '428915',
        label: 'Trésorerie XRP',
      },
    },
  },
  exchange: {
    globalFeePercent: 2.4,
    assetFeeOverrides: {
      BTC: 2.7,
      ETH: 2.3,
      USDT: 1.1,
      LTC: 2.1,
      SOL: 1.9,
      BNB: 2.2,
      XRP: 1.8,
    },
    minimumAmount: 50,
    maximumAmount: 15000,
    fixedRateMode: false,
    fixedRates: {
      paypalToCrypto: { BTC: 67340, ETH: 3492, USDT: 1, LTC: 87.4, SOL: 132.1, BNB: 414.2, XRP: 0.55 },
      cryptoToPaypal: { BTC: 66980, ETH: 3460, USDT: 0.995, LTC: 86.7, SOL: 130.4, BNB: 410.8, XRP: 0.54 },
      paysafecardToCrypto: { BTC: 66890, ETH: 3448, USDT: 0.992, LTC: 86.4, SOL: 129.5, BNB: 409.1, XRP: 0.535 },
      paysafecardToPaypal: { EUR: 0.93 },
    },
    warningMessage: 'Les montants présentés sont des estimations locales et restent soumis à vérification du paiement, du réseau et de la destination finale.',
    flowAvailability: {
      paypalToCrypto: true,
      cryptoToPaypal: true,
      paysafecardToCrypto: true,
      paysafecardToPaypal: true,
    },
    roundingDigits: 6,
    primaryCurrency: 'EUR',
    estimatedDelay: '5 à 30 minutes',
    validationMessages: {
      min: 'Le montant saisi est inférieur au minimum autorisé.',
      max: 'Le montant saisi dépasse la limite autorisée.',
      recipient: 'La destination de réception est requise pour continuer.',
      email: 'Veuillez renseigner une adresse email PayPal valide.',
      amount: 'Veuillez saisir un montant valide.',
    },
    sidebarMessages: [
      'Les paiements sont rapprochés avant toute émission ou tout dépôt.',
      'Les limites, frais et combinaisons actives sont entièrement pilotés depuis l’admin.',
      'Les dossiers invités et connectés restent consultables depuis le même appareil.',
    ],
  },
  market: {
    livePricingEnabled: false,
    assets: [
      { id: 'BTC', symbol: 'BTC', name: 'Bitcoin', iconUrl: '', fallbackIcon: '₿', visibleInMarket: true, visibleInExchange: true, price: 67340, change24h: 3.24, volume: 19800000000, marketCap: 1332000000000, position: 1, accent: '#f7931a', sparkline: sparkline(1, 2.1), featured: true },
      { id: 'ETH', symbol: 'ETH', name: 'Ethereum', iconUrl: '', fallbackIcon: 'Ξ', visibleInMarket: true, visibleInExchange: true, price: 3492, change24h: 2.18, volume: 9420000000, marketCap: 421000000000, position: 2, accent: '#627eea', sparkline: sparkline(2, 1.6), featured: true },
      { id: 'USDT', symbol: 'USDT', name: 'Tether', iconUrl: '', fallbackIcon: '₮', visibleInMarket: true, visibleInExchange: true, price: 1, change24h: 0.01, volume: 31400000000, marketCap: 101800000000, position: 3, accent: '#26a17b', sparkline: sparkline(3, 0.2), featured: true },
      { id: 'LTC', symbol: 'LTC', name: 'Litecoin', iconUrl: '', fallbackIcon: 'Ł', visibleInMarket: true, visibleInExchange: true, price: 87.4, change24h: -1.14, volume: 690000000, marketCap: 6650000000, position: 4, accent: '#345d9d', sparkline: sparkline(4, -0.4), featured: false },
      { id: 'SOL', symbol: 'SOL', name: 'Solana', iconUrl: '', fallbackIcon: 'S', visibleInMarket: true, visibleInExchange: true, price: 132.1, change24h: 4.08, volume: 1960000000, marketCap: 59700000000, position: 5, accent: '#14f195', sparkline: sparkline(5, 2.2), featured: true },
      { id: 'BNB', symbol: 'BNB', name: 'BNB', iconUrl: '', fallbackIcon: '◇', visibleInMarket: true, visibleInExchange: true, price: 414.2, change24h: 1.32, volume: 1240000000, marketCap: 63500000000, position: 6, accent: '#f3ba2f', sparkline: sparkline(6, 1.1), featured: false },
      { id: 'XRP', symbol: 'XRP', name: 'XRP', iconUrl: '', fallbackIcon: '✕', visibleInMarket: true, visibleInExchange: true, price: 0.55, change24h: -0.72, volume: 970000000, marketCap: 29900000000, position: 7, accent: '#23292f', sparkline: sparkline(7, -0.2), featured: false },
    ],
  },
  users: [
    { id: 'USR-1001', name: 'Lina Martin', email: 'lina.martin@example.com', createdAt: '2026-03-11T09:24:00.000Z', balance: 2840.45, status: 'Actif', kyc: 'Vérifié', lastActivity: '2026-03-27T09:22:00.000Z', tag: 'VIP', notes: 'Cliente récurrente sur les flux BTC et USDT.' },
    { id: 'USR-1002', name: 'Hugo Bernard', email: 'hugo.bernard@example.com', createdAt: '2026-03-16T14:12:00.000Z', balance: 1125.9, status: 'Actif', kyc: 'En cours', lastActivity: '2026-03-26T19:42:00.000Z', tag: 'Standard', notes: 'Préférence PayPal.' },
    { id: 'USR-1003', name: 'Mina Diallo', email: 'mina.diallo@example.com', createdAt: '2026-03-19T19:42:00.000Z', balance: 612.3, status: 'Suspendu', kyc: 'Non vérifié', lastActivity: '2026-03-21T15:03:00.000Z', tag: 'Review', notes: 'Compte suspendu pour vérification complémentaire.' },
    { id: 'USR-1004', name: 'Nicolas Rey', email: 'nicolas.rey@example.com', createdAt: '2026-03-21T08:30:00.000Z', balance: 4375.8, status: 'Vérifié', kyc: 'Vérifié', lastActivity: '2026-03-27T07:14:00.000Z', tag: 'Pro', notes: 'Volumes réguliers sur les flux crypto vers PayPal.' },
  ],
  transactions: [
    { id: 'TX-8K29FA', userId: 'USR-1001', userName: 'Lina Martin', userEmail: 'lina.martin@example.com', flowKey: 'cryptoToPaypal', type: 'Crypto → PayPal', paymentMethod: 'BTC', receiveMethod: 'PayPal', amountGross: 1234.5, fees: 33.33, amountNet: 1201.17, asset: 'BTC', assetQuantity: 0.0183, status: 'Confirmée', date: '2026-03-26T14:20:00.000Z', recipient: 'lina.martin@example.com', reference: 'CLX-8142', note: 'Traitement prioritaire' },
    { id: 'TX-1P94MC', userId: 'USR-1002', userName: 'Hugo Bernard', userEmail: 'hugo.bernard@example.com', flowKey: 'paypalToCrypto', type: 'PayPal → Crypto', paymentMethod: 'PayPal', receiveMethod: 'USDT', amountGross: 680, fees: 7.48, amountNet: 672.52, asset: 'USDT', assetQuantity: 672.52, status: 'En cours', date: '2026-03-26T09:05:00.000Z', recipient: 'TR7hugo8n9wallet5usdt2example77r5', reference: 'CLX-8129', note: 'Attente de rapprochement' },
    { id: 'TX-3D57QT', userId: 'USR-1004', userName: 'Nicolas Rey', userEmail: 'nicolas.rey@example.com', flowKey: 'paysafecardToPaypal', type: 'Paysafecard → PayPal', paymentMethod: 'Paysafecard', receiveMethod: 'PayPal', amountGross: 450, fees: 31.5, amountNet: 418.5, asset: 'EUR', assetQuantity: 0, status: 'En attente', date: '2026-03-25T18:44:00.000Z', recipient: 'nicolas.rey@example.com', reference: 'CLX-8097', note: 'Codes à vérifier' },
    { id: 'TX-6W21RL', userId: 'USR-1001', userName: 'Lina Martin', userEmail: 'lina.martin@example.com', flowKey: 'paysafecardToCrypto', type: 'Paysafecard → Crypto', paymentMethod: 'Paysafecard', receiveMethod: 'ETH', amountGross: 900, fees: 20.7, amountNet: 879.3, asset: 'ETH', assetQuantity: 0.255, status: 'Rejetée', date: '2026-03-24T16:12:00.000Z', recipient: '0x4bc8lina5wallet9eth2example73da11', reference: 'CLX-8044', note: 'Code incomplet' },
  ],
  reviews: reviewSamples,
  content: {
    fr: frContent,
    en: enContent,
  },
  notifications: {
    dashboardEnabled: true,
    items: [
      { id: 'NTF-1001', type: 'info', message: 'Les règlements PayPal sont rapprochés en priorité sur cette plage horaire.', duration: 4200, target: 'dashboard', display: 'toast', enabled: true, language: 'fr', createdAt: '2026-03-26T08:00:00.000Z' },
      { id: 'NTF-1002', type: 'warning', message: 'Un contrôle réseau supplémentaire peut s’appliquer sur les demandes XRP et BNB.', duration: 5600, target: 'exchange', display: 'banner', enabled: true, language: 'fr', createdAt: '2026-03-25T11:20:00.000Z' },
      { id: 'NTF-1003', type: 'info', message: 'Guest sessions stay available on this device until manually cleared.', duration: 4200, target: 'login', display: 'banner', enabled: true, language: 'en', createdAt: '2026-03-26T10:18:00.000Z' },
    ],
    history: [
      { id: 'NTF-1001', type: 'info', message: 'Les règlements PayPal sont rapprochés en priorité sur cette plage horaire.', duration: 4200, target: 'dashboard', display: 'toast', enabled: true, language: 'fr', createdAt: '2026-03-26T08:00:00.000Z' },
      { id: 'NTF-1002', type: 'warning', message: 'Un contrôle réseau supplémentaire peut s’appliquer sur les demandes XRP et BNB.', duration: 5600, target: 'exchange', display: 'banner', enabled: true, language: 'fr', createdAt: '2026-03-25T11:20:00.000Z' },
      { id: 'NTF-1003', type: 'info', message: 'Guest sessions stay available on this device until manually cleared.', duration: 4200, target: 'login', display: 'banner', enabled: true, language: 'en', createdAt: '2026-03-26T10:18:00.000Z' },
    ],
  },
  analytics: {
    volumeTotal: 2840000,
    totalTransactions: 18426,
    activeUsers: 3840,
    estimatedRevenue: 68120,
    averageTransaction: 612,
    completionRate: 98.9,
    averageProcessingMinutes: 11,
    averageRating: 4.8,
    peakHour: '18:00 - 20:00',
    dailyVolume7: [322000, 338000, 349000, 372000, 401000, 429000, 455000],
    dailyVolume30: [68000, 72000, 76000, 78800, 80500, 82100, 84600, 88100, 91200, 94800, 98000, 102200, 105600, 109800, 112300, 116000, 119500, 123400, 126000, 129200, 132400, 135600, 139000, 143600, 147900, 152300, 157400, 162200, 167900, 172600],
    topAssets: [
      { symbol: 'BTC', volume: 44 },
      { symbol: 'ETH', volume: 31 },
      { symbol: 'USDT', volume: 27 },
      { symbol: 'SOL', volume: 18 },
    ],
    flowDistribution: [
      { key: 'paypalToCrypto', label: 'PayPal → Crypto', value: 41 },
      { key: 'cryptoToPaypal', label: 'Crypto → PayPal', value: 28 },
      { key: 'paysafecardToCrypto', label: 'Paysafecard → Crypto', value: 17 },
      { key: 'paysafecardToPaypal', label: 'Paysafecard → PayPal', value: 14 },
    ],
    satisfactionBreakdown: {
      positive: 82,
      mixed: 14,
      critical: 4,
    },
  },
  objectives: {
    volumeTarget: 3200000,
    transactionTarget: 20000,
    userTarget: 4200,
    satisfactionTarget: 4.9,
    processingTimeTarget: 8,
    conversionTarget: 6.2,
  },
  security: {
    loginPageEnabled: true,
    maintenanceMode: false,
    maintenanceTitle: 'Plateforme en maintenance',
    maintenanceMessage: 'Une maintenance programmée est en cours. Merci de revenir dans quelques instants.',
  },
  adminAccess: {
    pinEnabled: false,
    pinHash: 'bfa0ec8bdf2946547879d50a68687ea32e2fa628db187357415858b633d194d9',
    pinProtectedTabs: ['payments', 'exchangeRules', 'security', 'adminsRoles'],
    allowAdminDuringMaintenance: true,
    sessionTimeoutMinutes: 90,
  },
  adminRoles: ROLE_PRESETS,
  admins: [
    {
      id: 'ADM-001',
      name: 'Aline Morel',
      email: 'owner@clyra.exchange',
      passwordHash: '37e9341462a838dcb27a77fbb32da4e2685ae7350c3022472f94eed5d4548c39',
      role: 'owner',
      level: 100,
      status: 'active',
      permissions: FULL_PERMISSIONS,
      createdAt: '2026-02-04T09:00:00.000Z',
      lastLogin: '2026-03-27T10:20:00.000Z',
      notes: 'Compte propriétaire de référence.',
    },
    {
      id: 'ADM-002',
      name: 'Marc Delorme',
      email: 'finance@clyra.exchange',
      passwordHash: 'e514f457534678f6184923cabe6bc215d3284ebea61bce5ac1974047b5810e19',
      role: 'financeAdmin',
      level: 78,
      status: 'active',
      permissions: ROLE_PRESETS.financeAdmin.permissions,
      createdAt: '2026-02-12T10:10:00.000Z',
      lastLogin: '2026-03-26T18:32:00.000Z',
      notes: 'Pilotage paiements et frais.',
    },
    {
      id: 'ADM-003',
      name: 'Sara Bernard',
      email: 'ops@clyra.exchange',
      passwordHash: '71764e75c0e7180d67d23c76d1752d3c688471cd7cc7af5b96aacb899754cdc6',
      role: 'operationsAdmin',
      level: 72,
      status: 'active',
      permissions: ROLE_PRESETS.operationsAdmin.permissions,
      createdAt: '2026-02-20T08:40:00.000Z',
      lastLogin: '2026-03-26T21:08:00.000Z',
      notes: 'Suivi quotidien des alertes et notifications.',
    },
    {
      id: 'ADM-004',
      name: 'Nora Petit',
      email: 'support@clyra.exchange',
      passwordHash: '26056cd70e6ad1a47b00d38e4332528ca9cecaab0120b52f7e59ecfd0b4c65cd',
      role: 'supportManager',
      level: 58,
      status: 'active',
      permissions: ROLE_PRESETS.supportManager.permissions,
      createdAt: '2026-02-22T11:14:00.000Z',
      lastLogin: '2026-03-25T14:54:00.000Z',
      notes: 'Support, notifications et suivi user.',
    },
    {
      id: 'ADM-005',
      name: 'Elias Martin',
      email: 'analyst@clyra.exchange',
      passwordHash: '71764e75c0e7180d67d23c76d1752d3c688471cd7cc7af5b96aacb899754cdc6',
      role: 'analyst',
      level: 36,
      status: 'active',
      permissions: ROLE_PRESETS.analyst.permissions,
      createdAt: '2026-02-28T15:18:00.000Z',
      lastLogin: '2026-03-24T12:15:00.000Z',
      notes: 'Lecture enrichie et exports.',
    },
  ],
  adminLogs: [
    { id: 'LOG-1001', adminId: 'ADM-001', email: 'owner@clyra.exchange', name: 'Aline Morel', role: 'owner', action: 'login', section: 'security', detail: 'Ouverture de session administrateur', severity: 'info', at: '2026-03-27T10:20:00.000Z' },
    { id: 'LOG-1002', adminId: 'ADM-002', email: 'finance@clyra.exchange', name: 'Marc Delorme', role: 'financeAdmin', action: 'save', section: 'payments', detail: 'Mise à jour des délais PayPal', severity: 'info', at: '2026-03-26T18:35:00.000Z' },
    { id: 'LOG-1003', adminId: 'ADM-003', email: 'ops@clyra.exchange', name: 'Sara Bernard', role: 'operationsAdmin', action: 'publish', section: 'notifications', detail: 'Publication d’un bandeau exchange', severity: 'warning', at: '2026-03-26T21:10:00.000Z' },
    { id: 'LOG-1004', adminId: 'ADM-001', email: 'owner@clyra.exchange', name: 'Aline Morel', role: 'owner', action: 'save', section: 'branding', detail: 'Palette principale mise à jour', severity: 'info', at: '2026-03-26T11:14:00.000Z' },
  ],
};
